cat ./bmp_examples/8_i/raw/france.bmp | ./imageprocessor HFLIP > ./bmp_examples/8_i/hflip/france.bmp
cat ./bmp_examples/8_i/raw/greenblue_square.bmp | ./imageprocessor HFLIP > ./bmp_examples/8_i/hflip/greenblue_square.bmp
cat ./bmp_examples/8_i/raw/handcrafted.bmp | ./imageprocessor HFLIP > ./bmp_examples/8_i/hflip/handcrafted.bmp
cat ./bmp_examples/8_i/raw/france.bmp | ./imageprocessor VFLIP > ./bmp_examples/8_i/vflip/france.bmp
cat ./bmp_examples/8_i/raw/greenblue_square.bmp | ./imageprocessor VFLIP > ./bmp_examples/8_i/vflip/greenblue_square.bmp
cat ./bmp_examples/8_i/raw/handcrafted.bmp | ./imageprocessor VFLIP > ./bmp_examples/8_i/vflip/handcrafted.bmp
cat ./bmp_examples/8_i/raw/france.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/8_i/grayscale/france.bmp
cat ./bmp_examples/8_i/raw/greenblue_square.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/8_i/grayscale/greenblue_square.bmp
cat ./bmp_examples/8_i/raw/handcrafted.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/8_i/grayscale/handcrafted.bmp
cat ./bmp_examples/16_565/raw/france.bmp | ./imageprocessor HFLIP > ./bmp_examples/16_565/hflip/france.bmp
cat ./bmp_examples/16_565/raw/greenblue_square.bmp | ./imageprocessor HFLIP > ./bmp_examples/16_565/hflip/greenblue_square.bmp
cat ./bmp_examples/16_565/raw/handcrafted.bmp | ./imageprocessor HFLIP > ./bmp_examples/16_565/hflip/handcrafted.bmp
cat ./bmp_examples/16_565/raw/france.bmp | ./imageprocessor VFLIP > ./bmp_examples/16_565/vflip/france.bmp
cat ./bmp_examples/16_565/raw/greenblue_square.bmp | ./imageprocessor VFLIP > ./bmp_examples/16_565/vflip/greenblue_square.bmp
cat ./bmp_examples/16_565/raw/handcrafted.bmp | ./imageprocessor VFLIP > ./bmp_examples/16_565/vflip/handcrafted.bmp
cat ./bmp_examples/16_565/raw/france.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/16_565/grayscale/france.bmp
cat ./bmp_examples/16_565/raw/greenblue_square.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/16_565/grayscale/greenblue_square.bmp
cat ./bmp_examples/16_565/raw/handcrafted.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/16_565/grayscale/handcrafted.bmp
cat ./bmp_examples/16_5551_rgb/raw/france.bmp | ./imageprocessor HFLIP > ./bmp_examples/16_5551_rgb/hflip/france.bmp
cat ./bmp_examples/16_5551_rgb/raw/greenblue_square.bmp | ./imageprocessor HFLIP > ./bmp_examples/16_5551_rgb/hflip/greenblue_square.bmp
cat ./bmp_examples/16_5551_rgb/raw/handcrafted.bmp | ./imageprocessor HFLIP > ./bmp_examples/16_5551_rgb/hflip/handcrafted.bmp
cat ./bmp_examples/16_5551_rgb/raw/france.bmp | ./imageprocessor VFLIP > ./bmp_examples/16_5551_rgb/vflip/france.bmp
cat ./bmp_examples/16_5551_rgb/raw/greenblue_square.bmp | ./imageprocessor VFLIP > ./bmp_examples/16_5551_rgb/vflip/greenblue_square.bmp
cat ./bmp_examples/16_5551_rgb/raw/handcrafted.bmp | ./imageprocessor VFLIP > ./bmp_examples/16_5551_rgb/vflip/handcrafted.bmp
cat ./bmp_examples/16_5551_rgb/raw/france.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/16_5551_rgb/grayscale/france.bmp
cat ./bmp_examples/16_5551_rgb/raw/greenblue_square.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/16_5551_rgb/grayscale/greenblue_square.bmp
cat ./bmp_examples/16_5551_rgb/raw/handcrafted.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/16_5551_rgb/grayscale/handcrafted.bmp
cat ./bmp_examples/16_5551_rgba/raw/france.bmp | ./imageprocessor HFLIP > ./bmp_examples/16_5551_rgba/hflip/france.bmp
cat ./bmp_examples/16_5551_rgba/raw/greenblue_square.bmp | ./imageprocessor HFLIP > ./bmp_examples/16_5551_rgba/hflip/greenblue_square.bmp
cat ./bmp_examples/16_5551_rgba/raw/handcrafted.bmp | ./imageprocessor HFLIP > ./bmp_examples/16_5551_rgba/hflip/handcrafted.bmp
cat ./bmp_examples/16_5551_rgba/raw/france.bmp | ./imageprocessor VFLIP > ./bmp_examples/16_5551_rgba/vflip/france.bmp
cat ./bmp_examples/16_5551_rgba/raw/greenblue_square.bmp | ./imageprocessor VFLIP > ./bmp_examples/16_5551_rgba/vflip/greenblue_square.bmp
cat ./bmp_examples/16_5551_rgba/raw/handcrafted.bmp | ./imageprocessor VFLIP > ./bmp_examples/16_5551_rgba/vflip/handcrafted.bmp
cat ./bmp_examples/16_5551_rgba/raw/france.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/16_5551_rgba/grayscale/france.bmp
cat ./bmp_examples/16_5551_rgba/raw/greenblue_square.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/16_5551_rgba/grayscale/greenblue_square.bmp
cat ./bmp_examples/16_5551_rgba/raw/handcrafted.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/16_5551_rgba/grayscale/handcrafted.bmp
cat ./bmp_examples/24_tc/raw/france.bmp | ./imageprocessor HFLIP > ./bmp_examples/24_tc/hflip/france.bmp
cat ./bmp_examples/24_tc/raw/greenblue_square.bmp | ./imageprocessor HFLIP > ./bmp_examples/24_tc/hflip/greenblue_square.bmp
cat ./bmp_examples/24_tc/raw/handcrafted.bmp | ./imageprocessor HFLIP > ./bmp_examples/24_tc/hflip/handcrafted.bmp
cat ./bmp_examples/24_tc/raw/france.bmp | ./imageprocessor VFLIP > ./bmp_examples/24_tc/vflip/france.bmp
cat ./bmp_examples/24_tc/raw/greenblue_square.bmp | ./imageprocessor VFLIP > ./bmp_examples/24_tc/vflip/greenblue_square.bmp
cat ./bmp_examples/24_tc/raw/handcrafted.bmp | ./imageprocessor VFLIP > ./bmp_examples/24_tc/vflip/handcrafted.bmp
cat ./bmp_examples/24_tc/raw/france.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/24_tc/grayscale/france.bmp
cat ./bmp_examples/24_tc/raw/greenblue_square.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/24_tc/grayscale/greenblue_square.bmp
cat ./bmp_examples/24_tc/raw/handcrafted.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/24_tc/grayscale/handcrafted.bmp
cat ./bmp_examples/32_tc_rgb/raw/france.bmp | ./imageprocessor HFLIP > ./bmp_examples/32_tc_rgb/hflip/france.bmp
cat ./bmp_examples/32_tc_rgb/raw/greenblue_square.bmp | ./imageprocessor HFLIP > ./bmp_examples/32_tc_rgb/hflip/greenblue_square.bmp
cat ./bmp_examples/32_tc_rgb/raw/handcrafted.bmp | ./imageprocessor HFLIP > ./bmp_examples/32_tc_rgb/hflip/handcrafted.bmp
cat ./bmp_examples/32_tc_rgb/raw/france.bmp | ./imageprocessor VFLIP > ./bmp_examples/32_tc_rgb/vflip/france.bmp
cat ./bmp_examples/32_tc_rgb/raw/greenblue_square.bmp | ./imageprocessor VFLIP > ./bmp_examples/32_tc_rgb/vflip/greenblue_square.bmp
cat ./bmp_examples/32_tc_rgb/raw/handcrafted.bmp | ./imageprocessor VFLIP > ./bmp_examples/32_tc_rgb/vflip/handcrafted.bmp
cat ./bmp_examples/32_tc_rgb/raw/france.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/32_tc_rgb/grayscale/france.bmp
cat ./bmp_examples/32_tc_rgb/raw/greenblue_square.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/32_tc_rgb/grayscale/greenblue_square.bmp
cat ./bmp_examples/32_tc_rgb/raw/handcrafted.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/32_tc_rgb/grayscale/handcrafted.bmp
cat ./bmp_examples/32_tc_rgba/raw/france.bmp | ./imageprocessor HFLIP > ./bmp_examples/32_tc_rgba/hflip/france.bmp
cat ./bmp_examples/32_tc_rgba/raw/greenblue_square.bmp | ./imageprocessor HFLIP > ./bmp_examples/32_tc_rgba/hflip/greenblue_square.bmp
cat ./bmp_examples/32_tc_rgba/raw/handcrafted.bmp | ./imageprocessor HFLIP > ./bmp_examples/32_tc_rgba/hflip/handcrafted.bmp
cat ./bmp_examples/32_tc_rgba/raw/france.bmp | ./imageprocessor VFLIP > ./bmp_examples/32_tc_rgba/vflip/france.bmp
cat ./bmp_examples/32_tc_rgba/raw/greenblue_square.bmp | ./imageprocessor VFLIP > ./bmp_examples/32_tc_rgba/vflip/greenblue_square.bmp
cat ./bmp_examples/32_tc_rgba/raw/handcrafted.bmp | ./imageprocessor VFLIP > ./bmp_examples/32_tc_rgba/vflip/handcrafted.bmp
cat ./bmp_examples/32_tc_rgba/raw/france.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/32_tc_rgba/grayscale/france.bmp
cat ./bmp_examples/32_tc_rgba/raw/greenblue_square.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/32_tc_rgba/grayscale/greenblue_square.bmp
cat ./bmp_examples/32_tc_rgba/raw/handcrafted.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/32_tc_rgba/grayscale/handcrafted.bmp
cat ./bmp_examples/raw_examples/raw/france.bmp | ./imageprocessor HFLIP > ./bmp_examples/raw_examples/hflip/france.bmp
cat ./bmp_examples/raw_examples/raw/greenblue_square.bmp | ./imageprocessor HFLIP > ./bmp_examples/raw_examples/hflip/greenblue_square.bmp
cat ./bmp_examples/raw_examples/raw/handcrafted.bmp | ./imageprocessor HFLIP > ./bmp_examples/raw_examples/hflip/handcrafted.bmp
cat ./bmp_examples/raw_examples/raw/france.bmp | ./imageprocessor VFLIP > ./bmp_examples/raw_examples/vflip/france.bmp
cat ./bmp_examples/raw_examples/raw/greenblue_square.bmp | ./imageprocessor VFLIP > ./bmp_examples/raw_examples/vflip/greenblue_square.bmp
cat ./bmp_examples/raw_examples/raw/handcrafted.bmp | ./imageprocessor VFLIP > ./bmp_examples/raw_examples/vflip/handcrafted.bmp
cat ./bmp_examples/raw_examples/raw/france.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/raw_examples/grayscale/france.bmp
cat ./bmp_examples/raw_examples/raw/greenblue_square.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/raw_examples/grayscale/greenblue_square.bmp
cat ./bmp_examples/raw_examples/raw/handcrafted.bmp | ./imageprocessor GRAYSCALE > ./bmp_examples/raw_examples/grayscale/handcrafted.bmp
